### ISSUE TITLE
robot.e is not ready in example.coffee

### ISSUE THREAD

**Issue by keke** [eedevops/hubot-enterprise#20]
Simple `hubot` robot example through `yo` generator.

`robot.e` is not initialized when `example.coffee` is loaded. See logs
```
[Tue Aug 09 2016 22:31:16 GMT+0800 (CST)] INFO Slack client now connected
[Tue Aug 09 2016 22:31:16 GMT+0800 (CST)] DEBUG Loading scripts from /Users/keke/Work/HPE/incub-lab/hubot-enterprise-cha/scripts
[Tue Aug 09 2016 22:31:16 GMT+0800 (CST)] ERROR hubot-enterprise not present, cannot run
[Tue Aug 09 2016 22:31:16 GMT+0800 (CST)] DEBUG Parsing help for /Users/keke/Work/HPE/incub-lab/hubot-enterprise-cha/scripts/example.coffee
[Tue Aug 09 2016 22:31:16 GMT+0800 (CST)] DEBUG Loading scripts from /Users/keke/Work/HPE/incub-lab/hubot-enterprise-cha/src/scripts
info: message received on reconnect with no registered callback:
[object Object]
[Tue Aug 09 2016 22:31:16 GMT+0800 (CST)] DEBUG Loading external-scripts from npm packages
[Tue Aug 09 2016 22:31:16 GMT+0800 (CST)] DEBUG Parsing help for /Users/keke/Work/HPE/incub-lab/hubot-enterprise-cha/node_modules/hubot-enterprise/src/0_bootstrap.coffee
[Tue Aug 09 2016 22:31:16 GMT+0800 (CST)] INFO /Users/keke/Work/HPE/incub-lab/hubot-enterprise-cha/node_modules/hubot-enterprise/src/0_bootstrap.coffee is using deprecated documentation syntax
[Tue Aug 09 2016 22:31:16 GMT+0800 (CST)] DEBUG Parsing help for /Users/keke/Work/HPE/incub-lab/hubot-enterprise-cha/node_modules/hubot-enterprise/src/admin.coffee
```

`example.coffee` is loaded before `0_bootstrap.coffee`

**Comment by mosheBelostotsky** [comment]
@keke hubot is loading 'scripts' before loading external-npm packages, therefore scripts in `scripts` directory cannot use hubot-enterprise...

**Comment by rqc** [comment]
@mosheBelostotsky This brings a very interesting scenario. If we want to develop an *integration* that uses `hubot-enterprise`, but we are doing it via the `scripts` directory, how can we make sure that `hubot-enterprise` is accessible?

**Comment by rqc** [comment]
@JonathanRosado this is interesting and it might have implications to the *docker* dev environment.

**Comment by keke** [comment]
@mosheBelostotsky this is also my guess. So what will be the suggestion to users of `hubot-enterprise`?

**Comment by mosheBelostotsky** [comment]
@keke Will be fixed by 0_bootstrap will load scripts from `enterprise_scripts` after robot.e object is ready.
updated also in eedevops/generator-hubot-enterprise
