### ISSUE TITLE
Consolidate Dockerfiles and use correct generators for hubot-enterprise docker image

### ISSUE THREAD

**Issue by rqc** [eedevops/hubot-enterprise#38]
In order to pipeline the building and tagging of the `hubot-enterprise` docker image we are planning to the following:

1. Consolidate the `Dockerfiles` [here](https://github.com/eedevops/hubot-dockerfile) and [here](https://github.com/eedevops/hubot-enterprise-dockerfile) into one `Dockerfile` into [this repository](https://github.com/eedevops/hubot-enterprise). This will allow auto-building docker images in docker hub that will include tags when they are pushed to this repo.
2. No `Dockerfile` will be added to the `generator-hubot-enterprise:app`, this is not needed, since `generator-hubot-enterprise:app` is not intended for development or deployment with `docker`. Supporting a `docker-compose.yml` within `generator-hubot-enterprise:script` should be enough for now.
3. Add a `docker-compose.yml` to this repository as well to streamline the development of `hubot-enterprise` package in itself. 

@mosheBelostotsky please confirm these details and let me know if you need assistance. Thanks!

@eitanshp @edagan @eitzhaki Please take note.

**Comment by eitanshp** [comment]
One thought - I don't want us tied-in into Swarm so I'm not sure docker-compose.yml is the obvious choice. Please consider a more generic (scripted) approach. This will allow us to support Kubernetes (which is in wide use as well).

**Comment by rqc** [comment]
@eitanshp I agree, but for **development** and **staging**, `docker-compose` has no match and since we want developer efficiency I still recommend it.

For **production** however, we could come up with a way to describe our services as a `kubertetes` `cube`. This project looks promising to convert a `docker-compose` config into that `kubernetes` https://github.com/kelseyhightower/compose2kube config files.

**Comment by mosheBelostotsky** [comment]
@rqc can we close this issue?

**Comment by rqc** [comment]
Yes!, great work @mosheBelostotsky and @JonathanRosado :smile:

**Comment by rqc** [comment]
@mosheBelostotsky didn't realize that we don't have the `docker-compose.yml` here.

**Comment by rqc** [comment]
Done.
