### ISSUE TITLE
[Enhancement] Consider removing the appended wildcard [ ]?(.*)

### ISSUE THREAD

**Issue by JonathanRosado** [eedevops/hubot-enterprise#39]
Although it is well documented, having HE append `[ ]?(.*)` to the base string auto-magically is very confusing IMO.

With the non-negotiable wildcard at the end, we're exposing devs to all kinds of subtle errors.

For example, suppose we have two actions.
1) "list something"
2) "list something in another format"

Action 1 and action 2 are translated by HE to /list something[ ]?(.*)?/ and /list something in another format[ ]?(.*)?/ respectively. Now, if I send the message "list something in another format" won't both listeners be triggered? This seems to happen on my end.

**Comment by rqc** [comment]
@edagan @eitzhaki we should discuss this.

**Comment by rqc** [comment]
@mosheBelostotsky do you have a suggestion to fix this unexpected user / developer behavior with `robot.e.create()`?

**Comment by rqc** [comment]
@JonathanRosado is this a blocker for `hubot-agm` ? Please list any commands that might not work because of this. Thanks!

**Comment by mosheBelostotsky** [comment]
@rqc @JonathanRosado , its exactly the same behavior as in hubot.hear
robot.hear /hello/
robot.hear /hello world/
both will be triggered.

Lets discuss it together with #40
