### ISSUE TITLE
[Feature] Optional extra parameter

### ISSUE THREAD

**Issue by JonathanRosado** [eedevops/hubot-enterprise#40]
As we previously discussed, we need better support for actions defined with regular expressions.

With the current structure of `robot.e.create`, it's not clear how a message with multiple regex criteria, such as `list defects discovered by (.+) in sprint ([^ ]+)(?: with filter(?:s)? (.*))?`, would fit within the structure. Furthermore, for my use case, adding a whitespace between the `action` and the `extra`, does not allow me to make the `extra` param optional.

**Comment by rqc** [comment]
@mosheBelostotsky I would like to see some suggestions on how to fix this. We need to take this as high-priority since this is **customer feedback**.

**Comment by rqc** [comment]
This one is related https://github.com/eedevops/hubot-enterprise/issues/40

**Comment by mosheBelostotsky** [comment]
9@rqc @JonathanRosado, here are some suggestions:
1. Let extra param be totally free regex: then, the user will add also the extra if needed (with spaces)
2. Set `extra_optional` flag. the it would be built in such way that it can be matched with or without
3. Document to the user that he need to create 2 functions. once for with and other for without extra
    See [hubot-bpm](https://github.com/HPSoftware/hubot-bpm/blob/master/src/invoke-script.coffee#L37) implementing something like this (using robot.respond)

Lets discuss tomorrow...

**Comment by mosheBelostotsky** [comment]
Hi, Following discussion with @JonathanRosado, here is the proposed solutions for this and #39 issues:

1. add `optional` parameter:
      - always add `$` to finish the line, so it will catch ONLY what it need to
      - the object will look like this: `extra: {re: /your regexp/i, optional: true/false}`
      - `optional=true` the `re` object will be wrapped with `(?: )?$`  (@JonathanRosado thanks for the regex!)
       Like this: `<product> <entity> <verb>(?: <extra.re>)?$`
    - `optional=false` the re will be prefixed with space: `<product> <verb> <entity> <extra.re>$`
    - if no `re` provided and `optional=false` then the call will be: `<product> <verb> <entity>$`
    - no `re` and `optional=true`: `[ ]?(.*)$` will be added
    - pros:
         - take some `heavy lifting` from the developer
         - make simpler to find and filter out similar calls in HE backend
   - cons:
         - more time to developer
         - usage may confuse the developer
2. replace extra with "free" regex
  - extra will be a regex, free for use to build, and will be added like this: `<product> <verb> <entity><re>`
  - pros:
    - easy do develop
    - give total control to the developer
  - cons:
    - may be confusing (need to remember to add space at the start for example)
    - may not work good with the final hubot enterprise recieveMiddleware

In both cases we can provide some example regular expressions for users

@eitzhaki @edagan @rqc please review.

**Comment by rqc** [comment]
@mosheBelostotsky and @JonathanRosado thanks for this, great work! I am inclined to support **2.**. I assume this *free regex* would be a key/value pair also? If so, perhaps we could call it `regex_suffix: <re>`.

**Comment by edagan** [comment]
@rqc @JonathanRosado @mosheBelostotsky @eitzhaki 
We discussed this internally and decided to go with object-based registrations.
We asked @mosheBelostotsky to implement this as an additional JSON object containing the extra parameters for a Hubot command. 
One of the object parameters allows the developer to set the extra as optional or mandatory. @mosheBelostotsky please document usage.
We believe this is an extensible, easy to use solution and it is a stepping-stone for our Help feature.

Thanks!
