### ISSUE TITLE
is there an change planed on Custom Messages functionality in near feature?

### ISSUE THREAD

**Issue by mmishalov** [eedevops/hubot-enterprise#51]
Hi in Wiki you mentioned that Custom Messages functionality will be replaced in version 0.2.0.
Is it still correct or something changed in original planing?

**Comment by mosheBelostotsky** [comment]
Hi, @mmishalov, We stick to the plan.
The **custom** messages will use `Cha` message template engine by @keke

**Comment by mmishalov** [comment]
@keke any update on this?

**Comment by mmishalov** [comment]
Conversation moved to github.hpe we can close this issue.
