### ISSUE TITLE
Support branches with special characters such as "/" (feature/mynewfeature) 

### ISSUE THREAD

**Issue by mmishalov** [eedevops/hubot-enterprise#62]
I would ask you to add the support of the branches with special characters such as "/" (feature/mynewfeature) since this syntax is part of suggested GitFlow BPs for many repository vendors such GitHub, BitBacket, Mercurial and etc.

**Comment by mosheBelostotsky** [comment]
@mmishalov This is a jenkins bug with excaping special characters in branch names and solved by 2 steps:
1. upgrade jenkins relevant plugin to latest
2. this change is breaking HE integration name auto-dicsover so need to update the pipeline plugin to create new sub-dir inside the workspace: this may take up to a day

**Comment by mmishalov** [comment]
@mosheBelostotsky thanks for quick response!
@eitzhaki can you please approve this effort? This is really important and should bring real value for integration development

**Comment by eitzhaki** [comment]
@mosheBelostotsky talk to me and to find the best time for it

**Comment by mosheBelostotsky** [comment]
@mmishalov fixed, can we close?
