### ISSUE TITLE
use robot.logger.debug|info (hubot logging) instead of console.log

### ISSUE THREAD

**Issue by mosheBelostotsky** [eedevops/hubot-enterprise#91]
https://github.com/eedevops/hubot-enterprise/blob/master/lib/authentication.coffee#L54
https://github.com/eedevops/hubot-enterprise/blob/master/src/0_bootstrap.coffee#L295

Why using console.log here?

**Comment by rqc** [comment]
@mosheBelostotsky Needed more coffee. Feel free to PR 😉

**Comment by mosheBelostotsky** [comment]
Fixed
